### ISSUE TITLE
[Feature Request] Support for Sonarr V4

### ISSUE THREAD

**Issue by emwedk** [TheUltimateC0der/alternatrr#2]
`Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: s.LanguageProfileId'.`

Expecting language profiles to exist

**Comment by TheUltimateC0der** [comment]
alternatrr is now Sonarr V4 compatible. Please be aware of the docker image URL change, since this is now only available on github via ghcr.io. I also updated the URL in the readme.
