### ISSUE TITLE
It looks like the repo on ghcr is no longer public?

### ISSUE THREAD

**Issue by m33ts4k0z** [TheUltimateC0der/alternatrr#5]
Hello,

Trying to pull the image that is compatible with sonarr v4 using Unraid, I get this error:

```
 -l net.unraid.docker.managed=dockerman 'ghcr.io/theultimatecoder/alternatrr:latest'
Unable to find image 'ghcr.io/theultimatecoder/alternatrr:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/theultimatecoder/alternatrr/manifests/latest": denied.
See 'docker run --help'.

The command failed.
```
Even trying to open that link directly into the web browser, returns the same error.

I think there is something with the access of this container?

**Comment by TheUltimateC0der** [comment]
Fixed by [#be41d113c32f53818af3a4d5c1eb9f3915c1ffba](https://github.com/TheUltimateC0der/alternatrr/commit/be41d113c32f53818af3a4d5c1eb9f3915c1ffba). This was actually my bad. I had a typo in the image URL. Now everything should work ;)

Thanks for reporting!

**Comment by m33ts4k0z** [comment]
Thanks for the fast answer.

Indeed its fine now. I have a question that you may be able to answer me. I have this edit on a show. I wonder where does the ServicesProvider entry comes from? Would you happen to know? Thank you in advance.

https://i.imgur.com/wjYQUzL.jpeg

**Comment by TheUltimateC0der** [comment]
These entries come from the so called "SkyHook". It's like a big cache that aggregates data from sources like TMDb, IMDb, TvDb and alike, and is used by radarr and sonarr for shows and movies.
